// Shared Tailwind class strings for patterns repeated across pages.
export const pageWidth = "mx-auto max-w-[1280px] px-8 max-tablet:px-[22px]";
export const eyebrow = "mb-[14px] text-[24px] font-medium tracking-[1px] text-primary max-tablet:text-[19px]";
export const kicker = "mb-[18px] text-[11px] font-semibold tracking-[1.8px] text-foreground";
export const textLink = "inline-flex items-center gap-2 border-b border-primary pb-[5px]";
export const centeredHero = "px-6 pt-[180px] pb-[110px] text-center max-tablet:pt-[145px] max-tablet:pb-20";
export const accountPage = "min-h-[65vh] pt-[155px] pb-[100px] max-[681px]:pt-[125px]";
export const accountHeader = "mb-12 flex flex-wrap items-center justify-between gap-6";
export const accountCard = "rounded-[24px] border border-forest/10 bg-white p-6 shadow-sm sm:p-8";
export const ownerSection = "min-h-[75vh] pt-[150px] pb-24 max-tablet:pt-[130px]";
export const ownerKicker = "mb-3 text-[11px] font-semibold tracking-[0.2em] text-forest";
export const ownerTitle = "text-[clamp(38px,4vw,58px)]";
export const ownerPanel = "rounded-[26px] border-forest/10 bg-white py-6 shadow-[0_12px_40px_-30px_rgba(34,76,64,0.4)] sm:py-8";
export const backLink = "mb-8 inline-flex items-center gap-2 text-[13px] font-medium text-forest hover:underline";
export const accountTitle = "mb-3 text-[44px] max-[681px]:text-[36px]";
export const brand = "flex items-center gap-[10px] whitespace-nowrap text-[20px] font-bold tracking-[0px]";
export const brandLogo = "size-10 rounded-full max-tablet:size-9";
export const formStack = "flex flex-col gap-[22px] [&_[data-slot=input]]:min-h-12";
export const articleMeta = "flex gap-6 text-[14px] text-muted-foreground";
export const pillAction = "inline-flex min-h-10 items-center justify-center gap-2 rounded-full bg-forest px-5 py-2 text-sm font-medium text-white hover:bg-forest/90 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary disabled:opacity-50";
